### ISSUE TITLE
c'è una difformità nella funzione _parse_date

### ISSUE THREAD

**Issue by claudiofrancesconi** [jacopo-j/TrenitaliaAPI#1]
ho dovuto aggiungere il comando:
string = string[:-3] + "00"
perché praticamente il fuso veniva formato come "+xx:xx" anziché "+xxxx"

**Comment by jacopo-j** [comment]
Se ti riferisci agli orari inviati dal client: il server dovrebbe parsare correttamente il fuso orario nel formato +HH:MM, è ciò che gli manda l'applicazione. Se invece hai problemi a parsare una risposta del server probabilmente è perché non stai usando Python 3.7 ma una versione precedente.

**Comment by claudiofrancesconi** [comment]
uso python 3.7 e ho problemi lato client. boh. sarà forse che sono su mac

**Comment by jacopo-j** [comment]
Potresti postare il traceback dell'errore?

**Comment by claudiofrancesconi** [comment]
ok. scusami ma oggi è il classico giorno che impazzisco con pip... su osx è sempre un delirio... comunque era un mismatch sul tzinfo, appena posso lo rilancio e lo posto

**Comment by albianto-polimi** [comment]
File "/Users/Alberto/Downloads/TrenitaliaAPI-master/trenitalia.py", line 136, in _parse_date
    return datetime.strptime(string, "%Y-%m-%dT%H:%M:%S%z")
TypeError: strptime() argument 1 must be str, not dict

Anche a me lo da su mac

**Comment by jacopo-j** [comment]
@albianto potresti postare il traceback completo e, se possibile, il codice che provoca questo errore? È riproducibile sempre?

**Comment by albianto-polimi** [comment]
Si, sempre.
Ad esempio facendo:
`print(tb.timetable(station_id="830001701", ttype="arrival"))`

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print(tb.timetable(station_id="830001701", ttype="arrival"))      
  File "/Users/Alberto/Downloads/TrenitaliaAPI-master/trenitalia.py", line 444, in timetable
    chkpdate = self._parse_date(train["LastReachedCheckPointBase"])
  File "/Users/Alberto/Downloads/TrenitaliaAPI-master/trenitalia.py", line 136, in _parse_date
    return datetime.strptime(string, "%Y-%m-%dT%H:%M:%S%z")
TypeError: strptime() argument 1 must be str, not dict
```

**Comment by jacopo-j** [comment]
Con 1e5806fc14e2acb1e155ab34465e91a091592fe4 ho risolto il bug segnalato da @albianto, che comunque è diverso rispetto a quello originariamente segnalato da @claudiofrancesconi. Siccome il bug originale continua ad essere non riproducibile, chiudo comunque questo issue.
