### ISSUE TITLE
Qual è il codice di una stazione?

### ISSUE THREAD

**Issue by marcoscale98** [jacopo-j/TrenitaliaAPI#8]
E' per caso un codice che inizia con S?

**Comment by jacopo-j** [comment]
I codici delle stazioni sono quelli restituiti dall'endpoint per la [ricerca delle stazioni](https://github.com/jacopo-j/TrenitaliaAPI/wiki/API-dell'app-Trenitalia#ricerca-stazioni), quelli delle stazioni italiane iniziano con 83.
